_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 49
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
architecture:
    value:
        - layer: Input
          units: 4
        - activation: relu
          layer: Dense
          units: 16
        - activation: softmax
          layer: Dense
          units: 3
batch_size:
    value: 32
epochs:
    value: 400
hidden_layer_size:
    value: 16
learning_rate:
    value: 0.001
